styletheoryapi:
  build: styletheory
  volumes:
    - ./styletheory/:/code
  log_driver: "syslog"
  log_opt:
    syslog-tag: "styletheoryapi"
  ports:
    - "8080:8080"
  environment:
    - NODE_ENV=development
  links:
    - styletheorymongo
styletheorymongo:
  build: styletheorymongo
  log_driver: "syslog"
  log_opt:
    syslog-tag: "styletheorymongo"
  ports:
    - "27017:27017"
